version: '3'
services:
  mysql:
    container_name: m-go-mysql
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    env_file:
      - .env

  adminer:
    container_name: m-go-adminer
    image: adminer:latest
    restart: always
    ports:
      - 8081:8080
    env_file:
      - .env

  prometheus:
    image: prom/prometheus
    container_name: m-go-prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  keycloak:
    container_name: m-go-keycloak
    command: start-dev
    image: quay.io/keycloak/keycloak:19.0.3
    volumes:
      - ./themes/:/opt/keycloak/themes/mgo/
      - ./providers/:/opt/keycloak/providers/
    depends_on:
      - mysql
    ports:
      - "8082:8080"
    env_file:
      - .env

  jaeger:
    image: jaegertracing/all-in-one:1.14
    container_name: m-go-jaeger
    ports:
      - 5778:5778
      - 9411:9411
      - 14250:14250
      - 14268:14268
      - 16686:16686
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
    env_file:
      - .env